export const hidespaces = [
	{
		id: 1,
		pack_id: 1,
		name: "anemone",
		asset: "anemone1_1.png",
		width: 2.56,
		height: 2.19,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 2,
		pack_id: 1,
		name: "beaverdam",
		asset: "beaverdam.png",
		width: 2.56,
		height: 2.47,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 0.2,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 3,
		pack_id: 1,
		name: "bush",
		asset: "bush.png",
		width: 1.97,
		height: 1.21,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 4,
		pack_id: 1,
		name: "tree",
		asset: "tree1_1.png",
		width: 3.04,
		height: 7.75,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: true,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 5,
		pack_id: 1,
		name: "volcano",
		asset: "volcano1_1.png",
		width: 1.94,
		height: 2.37,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 6,
		pack_id: 1,
		name: "igloo",
		asset: "igloo.png",
		width: 2.39,
		height: 1.4,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 7,
		pack_id: 1,
		name: "shipwreck",
		asset: "shipwreck.png",
		width: 10.49,
		height: 6.3,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 9,
		pack_id: 1,
		name: "pineapple",
		asset: "pineapple.png",
		width: 3.22,
		height: 3.68,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 10,
		pack_id: 1,
		name: "pearlstand",
		asset: "pearlstand.png",
		width: 1.68,
		height: 2.91,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 12,
		pack_id: 1,
		name: "pearlgoal",
		asset: "pearlgoal.png",
		width: 4.96,
		height: 3.83,
		hitbox:
			'{"shapes":[{"label":"body","type":"POLYGON","points":[[0.94747,0.99221,0.89293,0.1039,0.78384,0.06234,0.79798,0.99221]]}]}',
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 13,
		pack_id: 1,
		name: "swamptree",
		asset: "swamptree.png",
		width: 18.6,
		height: 10,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: true,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 14,
		pack_id: 1,
		name: "swampbush",
		asset: "swampbush.png",
		width: 7,
		height: 2.72,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 15,
		pack_id: 1,
		name: "swampbrokentree",
		asset: "swampbrokentree.png",
		width: 2.91,
		height: 2.31,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 16,
		pack_id: 1,
		name: "swamplillypad",
		asset: "swamplillypad.png",
		width: 6.24,
		height: 1.52,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 0.3,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 17,
		pack_id: 1,
		name: "swampdecoration1",
		asset: "swampdecoration1.png",
		width: 2.44,
		height: 1.32,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 18,
		pack_id: 1,
		name: "swamphalfmangrove",
		asset: "swamphalfmangrove.png",
		width: 2.6,
		height: 4.48,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 0,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 19,
		pack_id: 1,
		name: "cloud",
		asset: "cloud.png",
		width: 9.72,
		height: 2.41,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 0,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 21,
		pack_id: 1,
		name: "turbulentwater",
		asset: "turbulentwater.png",
		width: 2.56,
		height: 2.44,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 0.5,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 22,
		pack_id: 1,
		name: "stalactite1",
		asset: "stalactite1_1.png",
		width: 2.5,
		height: 1.87,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 23,
		pack_id: 1,
		name: "stalactitehole1",
		asset: "stalactitehole1.png",
		width: 4,
		height: 3.32,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 24,
		pack_id: 1,
		name: "bigstalactite",
		asset: "bigstalactite.png",
		width: 10.5,
		height: 15.69,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: true,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 25,
		pack_id: 1,
		name: "stalactite2",
		asset: "stalactite1_2.png",
		width: 2.5,
		height: 1.87,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 26,
		pack_id: 1,
		name: "stalactite3",
		asset: "stalactite1_3.png",
		width: 2.5,
		height: 1.87,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 27,
		pack_id: 1,
		name: "stalactite4",
		asset: "stalactite4.png",
		width: 2.5,
		height: 1.87,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 28,
		pack_id: 1,
		name: "stalactitehole2",
		asset: "stalactitehole2.png",
		width: 4,
		height: 3.32,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 29,
		pack_id: 3,
		name: "tree1",
		asset: "tree1.png",
		width: 3.86,
		height: 9.83,
		hitbox:
			'{"shapes":[{"label":"hide","type":"POLYGON","points":[[0,0,0,0.65615,1,0.65615,1,0]]},{"label":"body","type":"POLYGON","points":[[0.46632,0.65412,0.46632,1,0.56736,1,0.56736,0.65412]]},{"label":"food","type":"POLYGON","points":[[0.06736,0.02543,0.06736,0.63174,0.92228,0.63174,0.92228,0.02543]]}]}',
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: true,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "none",
		fish_level: null,
		excluding: null,
		including: "4,41",
	},
	{
		id: 30,
		pack_id: 3,
		name: "anemone",
		asset: "anemone3_1.png",
		width: 2.24,
		height: 2.4,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "<=",
		fish_level: 2,
		excluding: null,
		including: null,
	},
	{
		id: 31,
		pack_id: 3,
		name: "coldvar",
		asset: "coldvar.png",
		width: 2.19,
		height: 5.98,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 32,
		pack_id: 3,
		name: "coral1",
		asset: "coral3_1.png",
		width: 2.48,
		height: 2.18,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 33,
		pack_id: 3,
		name: "coral2",
		asset: "coral3_2.png",
		width: 2.26,
		height: 1.47,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 34,
		pack_id: 3,
		name: "coral3",
		asset: "coral3_3.png",
		width: 3.11,
		height: 3.25,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 35,
		pack_id: 3,
		name: "coral4",
		asset: "coral3_4.png",
		width: 5.06,
		height: 3.27,
		hitbox:
			'{"shapes":[{"label":"body","type":"POLYGON","points":[[0.09091,0.43119,0.5,1,0.70553,1,0.917,0.72477,0.55534,-0.00612]]}]}',
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: true,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 36,
		pack_id: 3,
		name: "kelpstrand",
		asset: "kelpstrand.png",
		width: 0.82,
		height: 4.37,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 37,
		pack_id: 3,
		name: "seasponge",
		asset: "seasponge.png",
		width: 2.04,
		height: 1.8,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "<=",
		fish_level: 2,
		excluding: null,
		including: null,
	},
	{
		id: 38,
		pack_id: 3,
		name: "tree2",
		asset: "tree2.png",
		width: 3.85,
		height: 9.83,
		hitbox:
			'{"shapes":[{"label":"hide","type":"POLYGON","points":[[0,0,0,0.65615,1,0.65615,1,0]]},{"label":"body","type":"POLYGON","points":[[0.46632,0.65412,0.46632,1,0.56736,1,0.56736,0.65412]]},{"label":"food","type":"POLYGON","points":[[0.06736,0.02543,0.06736,0.63174,0.92228,0.63174,0.92228,0.02543]]}]}',
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: true,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "none",
		fish_level: null,
		excluding: null,
		including: "4,41",
	},
	{
		id: 39,
		pack_id: 3,
		name: "tubeworms",
		asset: "tubeworms.png",
		width: 1.37,
		height: 2.1,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "<=",
		fish_level: 2,
		excluding: null,
		including: null,
	},
	{
		id: 40,
		pack_id: 3,
		name: "boat",
		asset: "boat.png",
		width: 14.14,
		height: 16.73,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 41,
		pack_id: 3,
		name: "bigboat",
		asset: "bigboat.png",
		width: 17.63,
		height: 22.56,
		hitbox:
			'{"shapes":[{"label":"hide","type":"CIRCLE","circle":{"x":0.67136,"y":0.21651,"radius":0.03189}},{"label":"hide","type":"CIRCLE","circle":{"x":0.77438,"y":0.29434,"radius":0.02841}},{"label":"hide","type":"CIRCLE","circle":{"x":0.85852,"y":0.36546,"radius":0.02332}},{"label":"hide","type":"POLYGON","points":[[0.84135,0.79334,0.79052,0.66667,0.6717,0.59313,0.75412,0.7284]]}]}',
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "<=",
		fish_level: 9,
		excluding: null,
		including: null,
	},
	{
		id: 42,
		pack_id: 2,
		name: "anemone",
		asset: "anemone2_1.png",
		width: 1.99,
		height: 2.4,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "<=",
		fish_level: 2,
		excluding: null,
		including: null,
	},
	{
		id: 43,
		pack_id: 2,
		name: "coral1",
		asset: "coral2_1.png",
		width: 5.47,
		height: 5.48,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: true,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 44,
		pack_id: 2,
		name: "coral2",
		asset: "coral2_2.png",
		width: 2.78,
		height: 2.46,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "<=",
		fish_level: 5,
		excluding: null,
		including: null,
	},
	{
		id: 45,
		pack_id: 2,
		name: "smallanemone",
		asset: "smallanemone.png",
		width: 0.76,
		height: 1.1,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "=",
		fish_level: 0,
		excluding: null,
		including: null,
	},
	{
		id: 46,
		pack_id: 2,
		name: "sponge1",
		asset: "sponge2_1.png",
		width: 0.57,
		height: 0.73,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "=",
		fish_level: 0,
		excluding: null,
		including: null,
	},
	{
		id: 47,
		pack_id: 2,
		name: "sponge2",
		asset: "sponge2_2.png",
		width: 1.33,
		height: 1.91,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "<=",
		fish_level: 1,
		excluding: null,
		including: null,
	},
	{
		id: 48,
		pack_id: 2,
		name: "tree",
		asset: "tree2_1.png",
		width: 5.13,
		height: 10.66,
		hitbox:
			'{"shapes":[{"label":"body","type":"POLYGON","points":[[0.423,0.99906,0.5692,0.99812,0.52242,0.32927,0.47173,0.32927]]},{"label":"food,body","type":"CIRCLE","circle":{"x":0.49858,"y":0.20263,"radius":0.27429}}]}',
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: true,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "none",
		fish_level: 4,
		excluding: null,
		including: "4,41",
	},
	{
		id: 49,
		pack_id: 3,
		name: "shipwreckb",
		asset: "shipwreckb.png",
		width: 10.18,
		height: 7.63,
		hitbox:
			'{"shapes":[{"label":"hide","type":"POLYGON","points":[[0.53438,0.18349,0.46169,0.26212,0.5334,0.3827,0.60413,0.30275]]},{"label":"food","type":"CIRCLE","circle":{"x":0.53045,"y":0.23329,"radius":0.01965}}]}',
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "<=",
		fish_level: 8,
		excluding: null,
		including: null,
	},
	{
		id: 50,
		pack_id: 10,
		name: "anchor",
		asset: "anchor.png",
		width: 1.75,
		height: 3.69,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 51,
		pack_id: 10,
		name: "baldcypressa",
		asset: "baldcypressa.png",
		width: 8.49,
		height: 17.74,
		hitbox:
			'{"shapes":[{"label":"body","type":"POLYGON","points":[[0.30389,0.99915,0.62014,0.99915,0.52297,0.82671,0.41696,0.83009],[0.41696,0.83009,0.52297,0.82671,0.5159,0.53423,0.42933,0.54269]]},{"label":"hide","type":"POLYGON","points":[[0.9576,0.48943,0.67845,0.39053,0.12898,0.40237,0.43286,0.54269],[0.12898,0.40237,0.67845,0.39053,0.92403,0.20541,0.82509,0.06086,0.25972,0.0186]]}]}',
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: true,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "none",
		fish_level: null,
		excluding: null,
		including: "41",
	},
	{
		id: 52,
		pack_id: 10,
		name: "baldcypressb",
		asset: "baldcypressb.png",
		width: 8.62,
		height: 17.89,
		hitbox:
			'{"shapes":[{"label":"body","type":"POLYGON","points":[[0.25175,1,0.62762,0.99916,0.50524,0.81559,0.38636,0.82481],[0.38636,0.82481,0.50524,0.81559,0.49476,0.48114,0.38287,0.48114]]},{"label":"hide","type":"POLYGON","points":[[0.98951,0.23638,0.60315,0.11735,0.22552,0.05365,0.38462,0.48198,0.49825,0.4803],[0.02448,0.26404,0.38462,0.48198,0.22552,0.05365],[0.96678,0.03018,0.22552,0.05365,0.60315,0.11735]]}]}',
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: true,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "none",
		fish_level: null,
		excluding: null,
		including: "41",
	},
	{
		id: 53,
		pack_id: 10,
		name: "cloudbig",
		asset: "cloudbig.png",
		width: 24.06,
		height: 7.97,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 0.5,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: true,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 54,
		pack_id: 10,
		name: "cloudcirrus",
		asset: "cloudcirrus.png",
		width: 29.91,
		height: 9.66,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 0.5,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 55,
		pack_id: 10,
		name: "cloudfar",
		asset: "cloudfar.png",
		width: 8.95,
		height: 2.8,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 0.5,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 56,
		pack_id: 10,
		name: "cloudnear",
		asset: "cloudnear.png",
		width: 14.58,
		height: 3.7,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 0.5,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 57,
		pack_id: 10,
		name: "cypressknob",
		asset: "cypressknob.png",
		width: 0.99,
		height: 1.76,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 58,
		pack_id: 10,
		name: "iciclea",
		asset: "iciclea.png",
		width: 1.09,
		height: 2.46,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 0,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 59,
		pack_id: 10,
		name: "pinea",
		asset: "pinea.png",
		width: 4.15,
		height: 11.64,
		hitbox:
			'{"shapes":[{"label":"body","type":"POLYGON","points":[[0.49386,0.67776,0.49386,1,0.543,1,0.543,0.67776]]},{"label":"hide,food","type":"POLYGON","points":[[0.07371,0.67513,0.92875,0.67776,0.63391,0.0035,0.44963,0.0035]]}]}',
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: true,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "none",
		fish_level: null,
		excluding: null,
		including: "41",
	},
	{
		id: 60,
		pack_id: 10,
		name: "pineb",
		asset: "pineb.png",
		width: 4.23,
		height: 11.63,
		hitbox:
			'{"shapes":[{"label":"hide,food","type":"POLYGON","points":[[0.05811,0.67694,0.90073,0.67958,0.61017,0.00176,0.42857,0.00176]]},{"label":"body","type":"POLYGON","points":[[0.50363,0.67606,0.50363,1,0.55206,1,0.55206,0.67606]]}]}',
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: true,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "none",
		fish_level: null,
		excluding: null,
		including: "41",
	},
	{
		id: 61,
		pack_id: 10,
		name: "pinec",
		asset: "pinec.png",
		width: 4.91,
		height: 11.74,
		hitbox:
			'{"shapes":[{"label":"food,hide","type":"POLYGON","points":[[0.90588,0.95203,0.54412,0.00369,0.39412,0.00369,0.13824,0.95326]]}]}',
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: true,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "none",
		fish_level: null,
		excluding: null,
		including: "41",
	},
	{
		id: 62,
		pack_id: 10,
		name: "pinesilhouettea",
		asset: "pinesilhouettea.png",
		width: 3.8,
		height: 10.64,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 63,
		pack_id: 10,
		name: "scotpine",
		asset: "scotpine.png",
		width: 5.82,
		height: 10.13,
		hitbox:
			'{"shapes":[{"label":"body","type":"POLYGON","points":[[0.47766,0.61303,0.47766,1,0.52062,1,0.52062,0.61303]]},{"label":"hide,food","type":"POLYGON","points":[[0.05155,0.59427,0.77835,0.62685,0.96048,0.34255,0.67869,0,0.33849,0,0.13746,0.19546]]}]}',
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: true,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "none",
		fish_level: null,
		excluding: null,
		including: "41",
	},
	{
		id: 64,
		pack_id: 10,
		name: "scotpinesilhouette",
		asset: "scotpinesilhouette.png",
		width: 5.35,
		height: 9.32,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 65,
		pack_id: 10,
		name: "seaweed",
		asset: "seaweed.png",
		width: 3.61,
		height: 2.36,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: true,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 68,
		pack_id: 4,
		name: "coral1",
		asset: "coral4_1.png",
		width: 1.65,
		height: 1.58,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 69,
		pack_id: 4,
		name: "coral2",
		asset: "coral4_2.png",
		width: 3.09,
		height: 2.57,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: true,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 70,
		pack_id: 4,
		name: "largevolcano",
		asset: "largevolcano.png",
		width: 5.75,
		height: 4.76,
		hitbox:
			'{"shapes":[{"label":"food","type":"CIRCLE","circle":{"x":0.46087,"y":0.04202,"radius":0.03478}},{"label":"hide","type":"POLYGON","points":[[0.97739,0.9979,0.4713,0.17857,0.12696,0.9958]]}]}',
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "<=",
		fish_level: 5,
		excluding: null,
		including: null,
	},
	{
		id: 71,
		pack_id: 4,
		name: "sponge1",
		asset: "sponge4_1.png",
		width: 0.55,
		height: 0.84,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "=",
		fish_level: 0,
		excluding: null,
		including: null,
	},
	{
		id: 72,
		pack_id: 4,
		name: "sponge2",
		asset: "sponge4_2.png",
		width: 1.24,
		height: 1.69,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "<=",
		fish_level: 1,
		excluding: null,
		including: null,
	},
	{
		id: 73,
		pack_id: 4,
		name: "stalactite1",
		asset: "stalactite4_1.png",
		width: 1.86,
		height: 1.62,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 74,
		pack_id: 4,
		name: "stalactite2",
		asset: "stalactite4_2.png",
		width: 2.64,
		height: 2.18,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 75,
		pack_id: 4,
		name: "stalactite3",
		asset: "stalactite4_3.png",
		width: 3.63,
		height: 2.36,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 76,
		pack_id: 4,
		name: "tubewormcluster",
		asset: "tubewormcluster.png",
		width: 1.72,
		height: 2.07,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "<=",
		fish_level: 2,
		excluding: null,
		including: null,
	},
	{
		id: 77,
		pack_id: 4,
		name: "volcano",
		asset: "volcano4_1.png",
		width: 2.19,
		height: 2.82,
		hitbox:
			'{"shapes":[{"label":"food","type":"CIRCLE","circle":{"x":0.55708,"y":0.04965,"radius":0.09132}},{"label":"hide","type":"POLYGON","points":[[0.99543,1.00355,0.55251,0.11348,0.02283,0.99645]]}]}',
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "<=",
		fish_level: 1,
		excluding: null,
		including: null,
	},
	{
		id: 78,
		pack_id: 4,
		name: "bubblevent",
		asset: "bubblevent.png",
		width: 2.76,
		height: 1.62,
		hitbox:
			'{"shapes":[{"label":"food","type":"CIRCLE","circle":{"x":0.43582,"y":0.23104,"radius":0.07246}}]}',
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 79,
		pack_id: 5,
		name: "eltaninantenna",
		asset: "eltaninantenna.png",
		width: 0.46,
		height: 1.53,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: true,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 80,
		pack_id: 5,
		name: "glassropesponge",
		asset: "glassropesponge.png",
		width: 0.33,
		height: 1.36,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "=",
		fish_level: 0,
		excluding: null,
		including: null,
	},
	{
		id: 81,
		pack_id: 5,
		name: "harpsponge",
		asset: "harpsponge.png",
		width: 3.03,
		height: 2.13,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: true,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 82,
		pack_id: 5,
		name: "parasolsponge1",
		asset: "parasolsponge1.png",
		width: 1.04,
		height: 1.55,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: true,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 83,
		pack_id: 5,
		name: "parasolsponge2",
		asset: "parasolsponge2.png",
		width: 1.01,
		height: 1.5,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: true,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 84,
		pack_id: 5,
		name: "pingpongtreesponge",
		asset: "pingpongtreesponge.png",
		width: 1.06,
		height: 1.37,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: true,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 85,
		pack_id: 5,
		name: "redtreecoral",
		asset: "redtreecoral.png",
		width: 2.14,
		height: 1.76,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: true,
		can_hide: true,
		exclusion_mode: "<=",
		fish_level: 2,
		excluding: null,
		including: null,
	},
	{
		id: 86,
		pack_id: 5,
		name: "ruffledsponge",
		asset: "ruffledsponge.png",
		width: 2.28,
		height: 1.42,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: true,
		can_hide: true,
		exclusion_mode: "=",
		fish_level: 0,
		excluding: null,
		including: null,
	},
	{
		id: 87,
		pack_id: 5,
		name: "venusflytrapanemone1",
		asset: "venusflytrapanemone1.png",
		width: 1.14,
		height: 1.3,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: true,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 88,
		pack_id: 5,
		name: "venusflytrapanemone2",
		asset: "venusflytrapanemone2.png",
		width: 1.15,
		height: 1.31,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: true,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
	{
		id: 89,
		pack_id: 5,
		name: "xenophyophore",
		asset: "xenophyophore.png",
		width: 1.94,
		height: 0.82,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: false,
		can_hide: true,
		exclusion_mode: "<=",
		fish_level: 1,
		excluding: null,
		including: null,
	},
	{
		id: 90,
		pack_id: 5,
		name: "zigzagcoral",
		asset: "zigzagcoral.png",
		width: 2.37,
		height: 2.36,
		hitbox: null,
		anchor_x: 0.5,
		anchor_y: 1,
		damageable: false,
		health: null,
		climbable: false,
		collidable: false,
		above: true,
		can_hide: false,
		exclusion_mode: null,
		fish_level: null,
		excluding: null,
		including: null,
	},
];
